// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type CreateProjectInput struct {
	RepositoryURL string `json:"repositoryUrl"`
	Branch        string `json:"branch"`
	Provider      string `json:"provider"`
	Domain        string `json:"domain"`
	Subdomain     string `json:"subdomain"`
}

type Mutation struct {
}

type Project struct {
	ID            string `json:"id"`
	Name          string `json:"name"`
	RepositoryURL string `json:"repositoryUrl"`
	Branch        string `json:"branch"`
	Provider      string `json:"provider"`
	Domain        string `json:"domain"`
	Subdomain     string `json:"subdomain"`
	CreatedAt     string `json:"createdAt"`
	UpdatedAt     string `json:"updatedAt"`
}

type Query struct {
}
