package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.90

import (
	"context"

	"github.com/damienhensen/deploy-flow/backend/graph/model"
	"github.com/damienhensen/deploy-flow/backend/internal/middelware"
)

// CreateProject is the resolver for the createProject field.
func (r *mutationResolver) CreateProject(ctx context.Context, input model.CreateProjectInput) (*model.Project, error) {
	userID, err := middelware.GetUserID(ctx)
	if err != nil {
		return nil, err
	}

	p, err := r.ProjectService.Create(
		userID,
		input.RepositoryURL,
		input.Branch,
		input.Provider,
		input.Domain,
		input.Subdomain,
	)

	if err != nil {
		return nil, err
	}

	return &model.Project{
		ID:            p.ID,
		Name:          p.Name,
		RepositoryURL: p.RepositoryURL,
		Branch:        p.Branch,
		Provider:      p.Provider,
		Domain:        p.Domain,
		Subdomain:     p.Subdomain,
		CreatedAt:     p.CreatedAt.String(),
		UpdatedAt:     p.UpdatedAt.String(),
	}, nil
}

// Projects is the resolver for the projects field.
func (r *queryResolver) Projects(ctx context.Context) ([]*model.Project, error) {
	userID, err := middelware.GetUserID(ctx)
	if err != nil {
		return nil, err
	}

	projects, err := r.ProjectService.FindAllForUser(userID)
	if err != nil {
		return nil, err
	}

	result := make([]*model.Project, 0, len(projects))

	for _, p := range projects {
		result = append(result, &model.Project{
			ID:            p.ID,
			Name:          p.Name,
			RepositoryURL: p.RepositoryURL,
			Branch:        p.Branch,
			Provider:      p.Provider,
			Domain:        p.Domain,
			Subdomain:     p.Subdomain,
			CreatedAt:     p.CreatedAt.String(),
			UpdatedAt:     p.UpdatedAt.String(),
		})
	}

	return result, nil
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
