package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.90

import (
	"context"
	"fmt"
	"time"

	"github.com/damienhensen/deploy-flow/backend/graph/model"
	"github.com/damienhensen/deploy-flow/backend/internal/middelware"
)

// CreateProject is the resolver for the createProject field.
func (r *mutationResolver) CreateProject(ctx context.Context, input model.CreateProjectInput) (*model.Project, error) {
	userID, err := middelware.GetUserID(ctx)
	if err != nil {
		return nil, err
	}

	p, err := r.ProjectService.Create(
		userID,
		input.Name,
		input.RepositoryURL,
		input.Branch,
		input.Provider,
		input.Domain,
		input.Subdomain,
	)

	if err != nil {
		return nil, err
	}

	return &model.Project{
		ID:            p.ID,
		Name:          p.Name,
		RepositoryURL: p.RepositoryURL,
		Branch:        p.Branch,
		Provider:      p.Provider,
		Domain:        p.Domain,
		Subdomain:     p.Subdomain,
		CreatedAt:     p.CreatedAt.String(),
		UpdatedAt:     p.UpdatedAt.String(),
	}, nil
}

// Projects is the resolver for the projects field.
func (r *queryResolver) Projects(ctx context.Context) ([]*model.Project, error) {
	userID, err := middelware.GetUserID(ctx)
	if err != nil {
		return nil, err
	}

	projects, err := r.ProjectService.FindAllForUser(userID)
	if err != nil {
		return nil, err
	}

	result := make([]*model.Project, 0, len(projects))

	for _, p := range projects {
		result = append(result, &model.Project{
			ID:            p.ID,
			Name:          p.Name,
			RepositoryURL: p.RepositoryURL,
			Branch:        p.Branch,
			Provider:      p.Provider,
			Domain:        p.Domain,
			Subdomain:     p.Subdomain,
			CreatedAt:     p.CreatedAt.String(),
			UpdatedAt:     p.UpdatedAt.String(),
		})
	}

	return result, nil
}

// GitRepositories is the resolver for the gitRepositories field.
func (r *queryResolver) GitRepositories(ctx context.Context, provider string) ([]*model.GitRepository, error) {
	userID, err := middelware.GetUserID(ctx)
	if err != nil {
		return nil, err
	}

	gitProvider, ok := r.GitProviders[provider]
	if !ok {
		return nil, fmt.Errorf("unsupported provider: %s", provider)
	}

	repositories, err := gitProvider.ListRepositories(ctx, userID)
	if err != nil {
		return nil, err
	}

	result := make([]*model.GitRepository, 0, len(repositories))
	for _, repo := range repositories {
		visibility := model.RepositoryVisibilityPublic
		if repo.Private {
			visibility = model.RepositoryVisibilityPrivate
		}

		result = append(result, &model.GitRepository{
			ID:            repo.ID,
			Name:          repo.Name,
			FullName:      repo.FullName,
			Owner:         repo.Owner,
			URL:           repo.URL,
			DefaultBranch: repo.DefaultBranch,
			UpdatedAt:     repo.UpdatedAt.Format(time.RFC3339),
			Visibility:    visibility,
		})
	}

	return result, nil
}

// GitBranches is the resolver for the gitBranches field.
func (r *queryResolver) GitBranches(ctx context.Context, provider string, owner string, repo string) ([]*model.GitBranch, error) {
	userID, err := middelware.GetUserID(ctx)
	if err != nil {
		return nil, err
	}

	gitProvider, ok := r.GitProviders[provider]
	if !ok {
		return nil, fmt.Errorf("unsupported provider: %s", provider)
	}

	branches, err := gitProvider.ListBranches(ctx, userID, owner, repo)
	if err != nil {
		return nil, err
	}

	result := make([]*model.GitBranch, 0, len(branches))

	for _, branch := range branches {
		result = append(result, &model.GitBranch{
			Name:                 branch.Name,
			UpdatedAt:            branch.UpdatedAt.Format(time.RFC3339),
			LastCommitAuthorName: branch.LastCommitAuthorName,
			LastCommitSha:        branch.LastCommitSha,
		})
	}

	return result, nil
}

// GitBranchDeploymentCheck is the resolver for the gitBranchDeploymentCheck field.
func (r *queryResolver) GitBranchDeploymentCheck(ctx context.Context, provider string, owner string, repo string, branch string) (*model.BranchDeploymentCheck, error) {
	userID, err := middelware.GetUserID(ctx)
	if err != nil {
		return nil, err
	}

	gitProvider, ok := r.GitProviders[provider]
	if !ok {
		return nil, fmt.Errorf("unsupported provider: %s", provider)
	}

	check, err := gitProvider.CheckDeploymentConfig(ctx, userID, owner, repo, branch)
	if err != nil {
		return nil, err
	}

	return &model.BranchDeploymentCheck{
		HasDockerCompose: check.HasDockerCompose,
		ComposeFilePath:  check.ComposeFilePath,
	}, nil
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
