package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.90

import (
	"context"

	"github.com/damienhensen/deploy-flow/backend/graph/model"
)

// CreateProject is the resolver for the createProject field.
func (r *mutationResolver) CreateProject(ctx context.Context, input model.CreateProjectInput) (*model.Project, error) {
	p, err := r.ProjectService.Create(
		input.Name,
		input.RepositoryURL,
		input.Branch,
		input.Provider,
	)

	if err != nil {
		return nil, err
	}

	return &model.Project{
		ID:            p.ID,
		Name:          p.Name,
		RepositoryURL: p.RepositoryURL,
		Branch:        p.Branch,
		Provider:      p.Provider,
		CreatedAt:     p.CreatedAt.String(),
		UpdatedAt:     p.UpdatedAt.String(),
	}, nil
}

// Projects is the resolver for the projects field.
func (r *queryResolver) Projects(ctx context.Context) ([]*model.Project, error) {
	projects, err := r.ProjectService.FindAll()
	if err != nil {
		return nil, err
	}

	result := make([]*model.Project, 0, len(projects))

	for _, p := range projects {
		result = append(result, &model.Project{
			ID:            p.ID,
			Name:          p.Name,
			RepositoryURL: p.RepositoryURL,
			Branch:        p.Branch,
			Provider:      p.Provider,
			CreatedAt:     p.CreatedAt.String(),
			UpdatedAt:     p.UpdatedAt.String(),
		})
	}

	return result, nil
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }

// !!! WARNING !!!
// The code below was going to be deleted when updating resolvers. It has been copied here so you have
// one last chance to move it out of harms way if you want. There are two reasons this happens:
//  - When renaming or deleting a resolver the old code will be put in here. You can safely delete
//    it when you're done.
//  - You have helper methods in this file. Move them out to keep these resolver files clean.
/*
	func (r *mutationResolver) CreateTodo(ctx context.Context, input model.NewTodo) (*model.Todo, error) {
	panic(fmt.Errorf("not implemented: CreateTodo - createTodo"))
}
func (r *queryResolver) Todos(ctx context.Context) ([]*model.Todo, error) {
	panic(fmt.Errorf("not implemented: Todos - todos"))
}
*/
